### ISSUE TITLE
Error: "Plugin not found, cannot call UAC::ExecCodeSegment"

### ISSUE THREAD

**Issue by TDI-tenderholt** [OpenMS/windows-installer#12]
I copied the UAC.dll file to the NSIS Plugin directory as directed by the README.

Few details:

* Windows 7
* Visual Studio 2015

I also tried installing VS 2010 Relocatable libraries and re-compiling the DLL using Visual Studio 2015 and the source from the NSIS Plugin site.

Any ideas?

**Comment by TDI-tenderholt** [comment]
Based on a comment on [StackOverflow](http://stackoverflow.com/a/23425023), there are now two plugin directories. Copying the UAC.dll file into both of these directories worked.

**Comment by hroest** [comment]
should we change the readme or make this automatic? @cbielow ?
